data:
  val_csv: '/ssd/datasets/tongue/five_fold_split/cross_validation/test.csv'
  img_dir: '/ssd/datasets/tongue/five_fold_split/dataset_origin/'
  batch_size: 32  
  num_workers: 4  

model:
  num_classes: 8 

training:
  save_dir: 'checkpoints/origin_fold5'

seed: 5201314
mode: "test"
