data:
  train_csv: '/ssd/datasets/tongue/five_fold_split/cross_validation/train_fold1.csv'
  val_csv: '/ssd/datasets/tongue/five_fold_split/cross_validation/val_fold1.csv'
  img_dir: '/ssd/datasets/tongue/five_fold_split/dataset_origin/'
  batch_size: 64
  num_workers: 8

model:
  num_classes: 8

optimizer:
  lr: 0.001
  weight_decay: 0.01

training:
  num_epochs: 33
  save_dir: "checkpoints/origin_fold1"
  
seed: 5201314
mode: "train" 
